### Array Creation

In [1]:
# Numerical Python
import numpy as np
np.__version__

'1.18.1'

In [3]:
arr1 = np.array([1,4,7,8,0])

In [4]:
type(arr1)

numpy.ndarray

In [7]:
# Using arange to create an array of 2 D
# arange --> similar to range(start, stop), where stop value is not included
# arange(start, stop, step)--> default start value is 0

arr2 = np.arange(1, 20, 2)

### Attributes

In [8]:
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
print(arr2.ndim)

1


In [12]:
#reshape --> to new dimension
arr3 = arr2.reshape(5, 2)  # 2,5
arr3.ndim

2

In [13]:
arr3

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [18]:
print(arr3.shape) # returns the nrows*ncols
print(arr1.size) # total number of elements in the array
print(arr1.dtype) # data type of the array

(5, 2)
5
int32


In [19]:
arr3[1][0]

5

In [20]:
# Sub-array with row indices 0, 1, 2
arr3[0:3]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [26]:
# linspace --> linearly spaced values in a interval
np.linspace(start = 20, stop = 50, num = 15)

array([20.        , 22.14285714, 24.28571429, 26.42857143, 28.57142857,
       30.71428571, 32.85714286, 35.        , 37.14285714, 39.28571429,
       41.42857143, 43.57142857, 45.71428571, 47.85714286, 50.        ])

### Stacking Arrays

In [27]:
# Use arange and reshape in a single line

a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)

In [28]:
print(a)
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [30]:
# hstack --> horizontal stack
np.hstack([a,b])  # np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [31]:
#vstack --> vertical stack
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])