### Array Creation

In [1]:
# Numerical Python
import numpy as np
np.__version__

'1.18.1'

In [2]:
arr1 = np.array([1,4,7,8,0])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
# Using arange to create an array of 2 D
# arange --> similar to range(start, stop), where stop value is not included
# arange(start, stop, step)--> default start value is 0

arr2 = np.arange(1, 20, 2)

### Attributes

In [5]:
print(arr2)

[ 1  3  5  7  9 11 13 15 17 19]


In [6]:
print(arr2.ndim)

1


In [7]:
#reshape --> to new dimension
arr3 = arr2.reshape(5, 2)  # 2,5
arr3.ndim

2

In [8]:
arr3

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [9]:
print(arr3.shape) # returns the nrows*ncols
print(arr1.size) # total number of elements in the array
print(arr1.dtype) # data type of the array

(5, 2)
5
int32


In [10]:
arr3[1][0]

5

In [11]:
# Sub-array with row indices 0, 1, 2
arr3[0:3]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [12]:
# linspace --> linearly spaced values in a interval
np.linspace(start = 20, stop = 50, num = 15)

array([20.        , 22.14285714, 24.28571429, 26.42857143, 28.57142857,
       30.71428571, 32.85714286, 35.        , 37.14285714, 39.28571429,
       41.42857143, 43.57142857, 45.71428571, 47.85714286, 50.        ])

### Stacking Arrays

In [13]:
# Use arange and reshape in a single line

a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)

In [14]:
print(a)
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [15]:
# hstack --> horizontal stack
np.hstack([a,b])  # np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [16]:
#vstack --> vertical stack
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

### Applying User Defined Functions

In [17]:
# Creating a function
def calculate(x):
    return x*x-5
calculate(45)

2020

In [18]:
calc = np.vectorize(calculate)

In [19]:
calc([1,2,3,4,5])

array([-4, -1,  4, 11, 20])

In [21]:
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [20]:
calc(b)

array([[116, 139, 164],
       [191, 220, 251],
       [284, 319, 356]])

## Random Module from Numpy

In [39]:
from numpy import random
random.rand()  # 0.78

0.37579580322027395

In [51]:
a = np.random.RandomState(1)
num = a.rand()
print(num)  # 0.41  0.41

0.417022004702574


In [56]:
a = np.random.RandomState(5)
num = a.rand()
print(num)  # 0.41  0.41

0.22199317108973948


In [57]:
random.randint(100)

58

In [58]:
random.randint(100, size =(2,2))

array([[74, 14],
       [76, 85]])

In [62]:
arr = random.choice([123,34,45,56,78,89,90,100,12,21,32,43], size = (2,2))

In [63]:
arr.ravel()

array([21, 43, 12, 21])